version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID:-minioadmin}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  api:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - redis
    command: ["bash", "-lc", "python - <<'PY'\nfrom redis import Redis\nfrom rq import Worker, Queue\nfrom app.config import settings\n\nredis = Redis.from_url(settings.redis_url)\nworker = Worker([Queue(settings.queue_name, connection=redis)], connection=redis)\nworker.work()\nPY\n"]

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    command: ["sh", "-lc", "rm -rf node_modules && npm install --force --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"]

volumes:
  minio_data:
